'use strict';

module.exports = {
  COMMENT_LENGTH_ERROR: `Комментарий содержит меньше 20 символов`,
  COMMENT_EMPTY_ERROR: `Сообщение не может быть пустым, напишите что-нибудь!`,
  TITLE_MIN_LENGTH_ERROR: `Заголовок должен быть не менее 30 символов`,
  TITLE_MAX_LENGTH_ERROR: `Заголовок должен быть не более 250 символов`,
  TITLE_EMPTY: `Заголовок не должен быть пустым`,
  PICTURE_EXTENCION_ERROR: `Допустимые расширения файлов: *.jpg, *.png`,
  CATEGORIES_MIN: `Должна быть выбрана минимум одна категория`,
  CATEGORIES_REQUIRED: `Не передан массив категорий`,
  DATA_STRING_REQUIRED: `Должна быть передана дата`,
  ANNOUNCE_MIN_LENGTH_ERROR: `Анонс должен быть не менее 30 символов`,
  ANNOUNCE_MAX_LENGTH_ERROR: `Анонс должен быть не более 250 символов`,
  ANNOUNCE_EMPTY: `Анонс не должен быть пустым`,
  FULL_TEXT_MAX: `Текст не должен превышать 1000 символов`,
  PARAMS_ERROR: `Параметр в url запроса, должен быть числом`,
  EMAIL_EMPTY_ERROR: `Ввведите email`,
  EMIAL_INCORRECT_ERROR: `Email в некорректном формате`,
  USER_NAME_EMPTY_ERROR: `Введите имя`,
  INCORRECT_USER_NAME: `В имени присутствуют недопустимые символы`,
  INCORRECT_USER_SURNAME: `В фамилии присутствуют недопустимые символы`,
  PASSWORD_EMPTY: `Введите пароль`,
  PASSWORD_MIN_LENGTH_ERROR: `Минимальная длинна пароля 6 символов`,
  RETRY_PASSWORD_EMPTY: `Повторите ввод пароля`,
  IDENTITY_RETRY_PASSWORD_ERROR: `Пароли не совпадают`,
};
