'use strict';

const ANSWER_ERROR = 404;
const SERVER_SERVICE_ERROR = 500;
const ARGUMENT_ERROR = 400;
const SALT_ROUNDS = 10;
const ADMIN_USER_ROLE_ID = 3;
const READER_USER_ROLE_ID = 2;

module.exports = {
  ANSWER_ERROR,
  SERVER_SERVICE_ERROR,
  ARGUMENT_ERROR,
  SALT_ROUNDS,
  ADMIN_USER_ROLE_ID,
  READER_USER_ROLE_ID,
};
